<?php

$factory->define(\App\Models\Suggestion::class, function (Faker\Generator $faker) {
    return [
        'ati_percentage_difference' => 0.5,
        'exchange' => 'bittrex',
        'coin' => 'ETH',
        'target' => 0,
        'exchange_trend' => 0,
        'btc_impact' => 0,
        'impact_1hr' => 0,
        'gap' => 0,
        'cpp' => 0,
        'prr' => 0,
        'btc_liquidity_bought' => 0,
        'btc_liquidity_sold' => 0,
        'target_score' => 0,
        'exchange_trend_score' => 0,
        'impact_1hr_change_score' => 0,
        'btc_impact_score' => 0,
        'btc_liquidity_score' => 0,
        'overall_score' => 0,
        'gap_arrow' => 0,
        'prr_arrow' => 0,
        'cpp_arrow' => 0,
        'overall_score_arrow' => 0,
        'btc_impact_arrow' => 0,
        'market_cap_arrow' => 0,
        'impact_1hr_change_arrow' => 0,
        'exchange_trend_arrow' => 0,
        'target_diff' => 0,
        'exchange_trend_diff' => 0,
        'btc_impact_diff' => 0,
        'impact_1hr_diff' => 0,
        'gap_diff' => 0,
        'cpp_diff' => 0,
        'prr_diff' => 0,
        'target_score_diff' => 0,
        'exchange_trend_score_diff' => 0,
        'btc_impact_score_diff' => 0,
        'btc_liquidity_score_diff' => 0,
        'btc_liquidity_bought_diff' => 0,
        'btc_liquidity_sold_diff' => 0,
        'impact_1hr_change_score_diff' => 0,
        'overall_score_diff' => 0,
        'base' => 0,
        'lowest_ask' => 0,
        'highest_bid' => 0,
        'market_cap' => 0,
        'market_cap_diff' => 0,
        'num_buys' => 0,
        'mean_buy_time' => 0,
        'num_sells' => 0,
        'mean_sell_time' => 0,
        'percentchange_score' => 0,
        'marketcap_score' => 0,
        'pricebtc_score' => 0
    ];
});
